### ISSUE TITLE
Aapt: error parsing xml: unbound prefix

### ISSUE THREAD

**Issue by MPADHQ-TonySmith** [docentTSR/xFallView#1]
Trying to incorporate this library into my project but I keep hitting the above mentioned error. 
Tony - Progressive App Developing Studios

**Comment by docentTSR** [comment]
@MPADHQ-TonySmith, hello.

Check please your "app tag" import for root element.
Must have:
`"xmlns:app="http://schemas.android.com/apk/res-auto"`

You can see, example
https://github.com/docentTSR/xFallView/blob/master/app/src/main/res/layout/activity_currencyfall.xml

And show your xml-file here with all elements.

**Comment by MPADHQ-TonySmith** [comment]
`<?xml version="1.0" encoding="utf-8"?>
<LinearLayout
	xmlns:android="http://schemas.android.com/apk/res/android"
	android:layout_width="match_parent"
	android:layout_height="match_parent"
	android:orientation="vertical">

	<LinearLayout
		android:id="@+id/linear1"
		android:layout_width="match_parent"
		android:layout_height="match_parent"
		android:orientation="vertical"
		android:gravity="bottom"
		android:layout_gravity="bottom">

		<LinearLayout
			android:id="@+id/linear2"
			android:layout_width="match_parent"
			android:layout_height="wrap_content"
			android:padding="8dp"
			android:background="#956F31"
			android:orientation="horizontal"
			android:gravity="bottom"
			android:layout_gravity="bottom"
			android:layout_weight="1">

			<LinearLayout
				android:id="@+id/linear3"
				android:layout_width="match_parent"
				android:layout_height="match_parent"
				android:padding="8dp"
				android:orientation="vertical"
				android:gravity="center_horizontal|center_vertical">

				<LinearLayout
					android:id="@+id/linear4"
					android:layout_width="match_parent"
					android:layout_height="wrap_content"
					android:padding="8dp"
					android:orientation="horizontal"
					android:gravity="center_horizontal|center_vertical">

					<TextView
						android:id="@+id/textview1"
						android:layout_width="wrap_content"
						android:layout_height="wrap_content"
						android:padding="8dp"
						android:text="Tree"
						android:textSize="30sp"
						android:textColor="#000000"/>

					<TextView
						android:id="@+id/logo"
						android:layout_width="wrap_content"
						android:layout_height="wrap_content"
						android:padding="8dp"
						android:gravity="center_horizontal|center_vertical"
						android:text="TextView"
						android:textSize="35sp"
						android:textColor="#FFFFFF"/>

					<TextView
						android:id="@+id/textview2"
						android:layout_width="wrap_content"
						android:layout_height="wrap_content"
						android:padding="8dp"
						android:text="Tree"
						android:textSize="30sp"
						android:textColor="#000000"/>

				</LinearLayout>

				<TextView
					android:id="@+id/monkey"
					android:layout_width="wrap_content"
					android:layout_height="wrap_content"
					android:padding="8dp"
					android:text="TextView"
					android:textSize="50sp"
					android:textColor="#000000"/>

			</LinearLayout>

		</LinearLayout>

		<Button
			android:id="@+id/start"
			android:layout_width="match_parent"
			android:layout_height="wrap_content"
			android:padding="8dp"
			android:background="#795548"
			android:text="START"
			android:textSize="20sp"
			android:textStyle="bold"
			android:textColor="#FFFFFF"/>

		<com.google.android.gms.ads.AdView
			xmlns:ads="http://schemas.android.com/apk/res-auto"
			android:id="@+id/adView"
			android:layout_width="wrap_content"
			android:layout_height="wrap_content"
			android:layout_centerHorizontal="true"
			android:layout_alignParentBottom="true"
			ads:adSize="BANNER"
			ads:adUnitId="ca-app-pub-6314399559271167/8326097951">

		</com.google.android.gms.ads.AdView>

	</LinearLayout>
	
	<com.docentTSR.xFallView.views.XFallView
		android:id="@+id/x_fall_view"
		android:layout_width="match_parent"
		android:layout_height="match_parent"
		app:viewsCount="80"
		app:minSpeed="60"
		app:maxSpeed="95"
		app:minAlpha="10"
		app:maxAlpha="255"
		app:minScale="30"
		app:maxScale="60"
		app:wind="windy"
		app:rotate="on"
		app:srcArray="@array/drawable_array"/>
	
</LinearLayout>
`
@docentTSR

**Comment by MPADHQ-TonySmith** [comment]
My gradle dependencies:
`  compile fileTree(dir: 'libs', include: ['*.jar'])
    compile 'com.google.android.gms:play-services-ads:'
	compile 'com.github.docentTSR:xFallView:0.9.3'`

**Comment by MPADHQ-TonySmith** [comment]
I just found by adding these as dependencies to my app:
` compile 'com.android.support:appcompat-v7:27.1.1'
    compile 'com.android.support:design:27.1.1' `

I could remove that error... But then I end up with four aapt errors.

**Comment by docentTSR** [comment]
@MPADHQ-TonySmith 
**Where is your root container?**
`<LinearLayout
--android:id="@+id/linear1"
--some code
</LinearLayout>

<com.docentTSR.xFallView.views.XFallView
--some code 
/>
`
**Your current structure is incorrect**

**see example, again**
https://github.com/docentTSR/xFallView/blob/master/app/src/main/res/layout/activity_currencyfall.xml

**Comment by MPADHQ-TonySmith** [comment]
Have changed where it goes now.
`<?xml version="1.0" encoding="utf-8"?>
<ScrollView
	xmlns:android="http://schemas.android.com/apk/res/android"
	android:layout_height="wrap_content"
	android:layout_width="wrap_content">

	<LinearLayout
		android:layout_width="match_parent"
		android:layout_height="match_parent"
		android:orientation="vertical">

	<com.docentTSR.xFallView.views.XFallView
		android:id="@+id/test_xfall_view"
		android:layout_width="match_parent"
		android:layout_height="match_parent"
		app:maxAlpha="230"
		app:maxScale="80"
		app:maxSpeed="100"
		app:minAlpha="5"
		app:minScale="50"
		app:minSpeed="70"
		app:rotate="on"
		app:srcArray="@array/x_views_currency_array"
		app:viewsCount="100"/>

		<LinearLayout
			android:id="@+id/linear9"
			android:layout_width="match_parent"
			android:layout_height="match_parent">

			<LinearLayout
				android:id="@+id/linear1"
				android:layout_width="match_parent"
				android:layout_height="match_parent"
				android:background="#A1887F"
				android:orientation="vertical">

				<LinearLayout
					android:id="@+id/linear4"
					android:layout_width="match_parent"
					android:layout_height="wrap_content"
					android:background="#66BB6A"
					android:orientation="horizontal"
					android:padding="8dp">

					<TextView
						android:id="@+id/textview1"
						android:layout_width="wrap_content"
						android:layout_height="wrap_content"
						android:padding="8dp"
						android:text="Score"
						android:textColor="#FFFFFF"
						android:textSize="20sp"
						android:textStyle="bold"/>

					<TextView
						android:id="@+id/monkey"
						android:layout_width="wrap_content"
						android:layout_height="wrap_content"
						android:padding="8dp"
						android:textColor="#FFFFFF"
						android:textSize="20sp"
						android:textStyle="bold"/>

					<TextView
						android:id="@+id/score"
						android:layout_width="wrap_content"
						android:layout_height="wrap_content"
						android:paddingBottom="8dp"
						android:paddingRight="8dp"
						android:paddingTop="8dp"
						android:text="0"
						android:textColor="#FFFFFF"
						android:textSize="20sp"/>

					<LinearLayout
						android:layout_width="match_parent"
						android:layout_height="match_parent"
						android:gravity="right"
						android:orientation="horizontal">

						<LinearLayout
							android:layout_height="wrap_content"
							android:layout_width="wrap_content"
							android:orientation="vertical">

							<Button
								android:id="@+id/video_life"
								android:layout_width="wrap_content"
								android:layout_height="wrap_content"
								android:gravity="center"
								android:padding="2dp"
								android:text="+1❤"
								android:textAlignment="center"
								android:textColor="#3B120F"
								android:textSize="20sp"
								android:textStyle="bold"
								android:alpha=".5"/>

							<Button
								android:layout_height="wrap_content"
								android:layout_width="wrap_content"
								android:text="Button"/>

						</LinearLayout>

					</LinearLayout>

				</LinearLayout>

				<LinearLayout
					android:id="@+id/linear5"
					android:layout_width="match_parent"
					android:layout_height="wrap_content"
					android:background="#FFFFFF"
					android:orientation="horizontal"
					android:padding="8dp">

					<TextView
						android:id="@+id/lives"
						android:layout_width="wrap_content"
						android:layout_height="wrap_content"
						android:layout_weight="1"
						android:gravity="center_horizontal|center_vertical"
						android:padding="8dp"
						android:text="TextView"
						android:textColor="#000000"
						android:textSize="40sp"/>

				</LinearLayout>

				<LinearLayout
					android:id="@+id/linear6"
					android:layout_width="match_parent"
					android:layout_height="40dp"
					android:background="#FFFFFF"
					android:gravity="center_vertical"
					android:orientation="horizontal">

					<TextView
						android:id="@+id/deco1"
						android:layout_width="wrap_content"
						android:layout_height="wrap_content"
						android:padding="8dp"
						android:text="TextView"
						android:textColor="#000000"
						android:textSize="18sp"/>

				</LinearLayout>

				<LinearLayout
					android:id="@+id/linear2"
					android:layout_width="match_parent"
					android:layout_height="wrap_content"
					android:orientation="horizontal">

					<Button
						android:id="@+id/mole1"
						android:layout_width="wrap_content"
						android:layout_height="wrap_content"
						android:layout_weight="1"
						android:background="@android:color/transparent"
						android:gravity="center_horizontal|center_vertical"
						android:padding="8dp"
						android:text="●"
						android:textColor="#000000"
						android:textSize="50sp"
						android:textStyle="bold"/>

					<Button
						android:id="@+id/mole2"
						android:layout_width="wrap_content"
						android:layout_height="wrap_content"
						android:layout_weight="1"
						android:background="@android:color/transparent"
						android:gravity="center_horizontal|center_vertical"
						android:padding="8dp"
						android:text="●"
						android:textColor="#000000"
						android:textSize="50sp"
						android:textStyle="bold"/>

					<Button
						android:id="@+id/mole3"
						android:layout_width="wrap_content"
						android:layout_height="wrap_content"
						android:layout_weight="1"
						android:background="@android:color/transparent"
						android:gravity="center_horizontal|center_vertical"
						android:padding="8dp"
						android:text="●"
						android:textColor="#000000"
						android:textSize="50sp"
						android:textStyle="bold"/>

				</LinearLayout>

				<LinearLayout
					android:id="@+id/linear3"
					android:layout_width="match_parent"
					android:layout_height="wrap_content"
					android:orientation="horizontal">

					<Button
						android:id="@+id/mole4"
						android:layout_width="wrap_content"
						android:layout_height="wrap_content"
						android:layout_weight="1"
						android:background="@android:color/transparent"
						android:gravity="center_horizontal|center_vertical"
						android:padding="8dp"
						android:text="●"
						android:textColor="#000000"
						android:textSize="50sp"
						android:textStyle="bold"/>

					<Button
						android:id="@+id/mole5"
						android:layout_width="wrap_content"
						android:layout_height="wrap_content"
						android:layout_weight="1"
						android:background="@android:color/transparent"
						android:gravity="center_horizontal|center_vertical"
						android:padding="8dp"
						android:text="●"
						android:textColor="#000000"
						android:textSize="50sp"
						android:textStyle="bold"/>

					<Button
						android:id="@+id/mole6"
						android:layout_width="wrap_content"
						android:layout_height="wrap_content"
						android:layout_weight="1"
						android:background="@android:color/transparent"
						android:gravity="center_horizontal|center_vertical"
						android:padding="8dp"
						android:text="●"
						android:textColor="#000000"
						android:textSize="50sp"
						android:textStyle="bold"/>

				</LinearLayout>

				<LinearLayout
					android:id="@+id/linear7"
					android:layout_width="match_parent"
					android:layout_height="40dp"
					android:background="#FFFFFF"
					android:gravity="center_vertical"
					android:orientation="horizontal">

					<TextView
						android:id="@+id/deco2"
						android:layout_width="wrap_content"
						android:layout_height="wrap_content"
						android:padding="8dp"
						android:text="TextView"
						android:textColor="#000000"
						android:textSize="20sp"/>

				</LinearLayout>

				<LinearLayout
					android:id="@+id/linear8"
					android:layout_width="match_parent"
					android:layout_height="match_parent"
					android:background="#66BB6A"
					android:gravity="bottom|center_horizontal"
					android:orientation="vertical">

					<TextView
						android:id="@+id/notify"
						android:layout_width="wrap_content"
						android:layout_height="wrap_content"
						android:padding="8dp"
						android:textColor="#FFFFFF"
						android:textSize="20sp"
						android:textStyle="bold"/>

					<com.google.android.gms.ads.AdView
						xmlns:ads="http://schemas.android.com/apk/res-auto"
						android:id="@+id/adView"
						android:layout_width="match_parent"
						android:layout_height="wrap_content"
						android:layout_alignParentBottom="true"
						android:layout_centerHorizontal="true"
						ads:adSize="BANNER"
						ads:adUnitId="ca-app-pub-6314399559271167/9451477366">

					</com.google.android.gms.ads.AdView>

				</LinearLayout>

			</LinearLayout>

		</LinearLayout>
		
	</LinearLayout>

</ScrollView>
`
Still getting the same error, I am using A-IDE an Android IDE because I don't have a PC, but maybe that is the problem.
@docentTSR

**Comment by docentTSR** [comment]
@MPADHQ-TonySmith 
I do not see "android" and "app" import into root LinearLayout!
`xmlns:android="http://schemas.android.com/apk/res/android"
xmlns:app="http://schemas.android.com/apk/res-auto"
`
